### ISSUE TITLE
[BUG]: Attendee email and name are the same (both are email)

### ISSUE THREAD

**Issue by FeralFlora** [cloud-atlas-ai/obsidian-ics#111]
Not sure if this should be labelled a bug or a feature request. But in any case, the issue is that name and email are both the email of the attendee. This is a) redundant and b) a loss of information, since the actual name is not available. I'm trying to implement the workflow requested [here](https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74#discussioncomment-8519107) (formatting the name as a link to the person folder), but without the name, it's not possible. Unless perhaps if you add the email as an alias to the note, but that's something you can only do after the note has been created, in this scenario.

So I'm wondering if this is intentional, which it seems to be based on [this](https://github.com/cloud-atlas-ai/obsidian-ics/issues/19#issuecomment-1773976408) and [this](https://github.com/cloud-atlas-ai/obsidian-ics/blob/dad4fc23047faa095bf486ad13f2c7173188ac47/src/main.ts#L104-L120), and if so, why? Is it because the name of the attendee is simply not available? If so, bummer.

**Comment by muness** [comment]
Hi @FeralFlora - I noticed the same and it may be worth adding a note or alternative handling to https://github.com/cloud-atlas-ai/obsidian-ics/blob/dad4fc23047faa095bf486ad13f2c7173188ac47/src/main.ts#L104-L120 

I downloaded several ics files from different providers and `CN` (canonical name) is often the email address instead of the name. I don't know why this is the case. It is not _always_ email, sometimes coming through as the attendee's name.

I'd rather not manipulate the data as it comes through, so could see adding another field or two with processed name & email if you think that is what most people expect.

**Comment by muness** [comment]
For reference: https://www.kanzaki.com/docs/ical/attendee.html

**Comment by FeralFlora** [comment]
> For reference: https://www.kanzaki.com/docs/ical/attendee.html

Thanks for the link:

> The property parameter CN is for the common or displayable name associated with the calendar address
Strange how your and my experience doesn't line up with this ☝️ 

> I'd rather not manipulate the data as it comes through, so could see adding another field or two with processed name & email if you think that is what most people expect.
I understand, that makes sense. If something like that is possible, it would be great, but what would you process, if CN is just the email?

**Comment by FeralFlora** [comment]
I've shared my current attendee implementation here: https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74#discussioncomment-8522435
